import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'OurFable.ai terms of service. Read about our terms, digital storybook delivery, and refund policies.',
  alternates: { canonical: 'https://ourfable.ai/terms' },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="sticky top-0 z-50 flex justify-between items-center px-6 py-4 bg-white/90 backdrop-blur-xl border-b border-brand-border">
        <Link href="/" className="font-display text-2xl font-extrabold text-brand-ink">
          Our<span className="text-brand-teal">Fable</span>
          <span className="text-brand-ink-muted text-sm font-body">.ai</span>
        </Link>
        <Link href="/" className="btn-secondary text-sm py-2 px-4">
          Back to Home
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="font-display text-4xl font-extrabold text-brand-ink mb-2">Terms of Service</h1>
        <p className="text-brand-ink-muted font-body text-sm mb-10">Last updated: February 19, 2026</p>

        <div className="prose prose-gray max-w-none font-body space-y-8">
          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">1. Acceptance of Terms</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed">
              By accessing or using OurFable.ai (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. You must be at least 18 years old or have parental/guardian consent to create an account.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">2. Description of Service</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed">
              OurFable.ai is an AI-powered platform that creates personalized children&apos;s storybooks. Users upload a photo and provide story details, and our AI generates illustrated storybooks available in digital and premium hardcover formats.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You may not transfer or share your account with others.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">4. Digital Product Delivery</h2>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>Digital storybooks are delivered instantly upon successful AI generation.</li>
              <li>Generation typically completes within 3 minutes but may take longer during high demand.</li>
              <li>Digital books are accessible through your OurFable account on any device with a web browser.</li>
              <li>We do not guarantee specific generation results. Each book is uniquely generated by AI.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">5. Hardcover Books</h2>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>Premium hardcover books are printed on demand and shipped to your provided address.</li>
              <li>Estimated delivery is 5-7 business days within the United States.</li>
              <li>International shipping may take additional time and incur extra fees.</li>
              <li>Shipping addresses must be accurate. We are not responsible for deliveries to incorrect addresses.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">6. Pricing &amp; Payment</h2>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>Digital storybooks: $14.99 (one-time purchase).</li>
              <li>Hardcover storybooks: $34.99 (one-time purchase, includes digital access).</li>
              <li>All prices are in USD and may be subject to applicable taxes.</li>
              <li>Payments are processed securely through Stripe. We do not store payment card details.</li>
              <li>Prices may change at any time. Changes will not affect previously completed purchases.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">7. Refund Policy</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed mb-3">
              Because storybooks are personalized digital products generated uniquely for each customer:
            </p>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li><strong className="text-brand-ink">Digital books:</strong> Refunds are available if AI generation fails and cannot be retried successfully. We do not offer refunds based on subjective dissatisfaction with AI-generated content.</li>
              <li><strong className="text-brand-ink">Hardcover books:</strong> Refunds or reprints are available for printing defects, shipping damage, or significant quality issues. Contact us within 14 days of delivery with photos of the issue.</li>
              <li>To request a refund, email <a href="mailto:support@ourfable.ai" className="text-brand-teal hover:underline">support@ourfable.ai</a> with your order details.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">8. AI-Generated Content Disclaimer</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed mb-3">
              All storybook content — including text and illustrations — is generated by artificial intelligence. Please note:
            </p>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>AI-generated content may vary in quality and may not always perfectly match your expectations.</li>
              <li>Character likeness in illustrations is AI-approximated and may not be an exact representation.</li>
              <li>We review AI outputs for safety but cannot guarantee all content will be free of imperfections.</li>
              <li>Stories are generated to be age-appropriate, but parents should review content before sharing with children.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">9. Intellectual Property</h2>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>You retain rights to photos you upload.</li>
              <li>AI-generated storybook content (text and illustrations) is licensed to you for personal, non-commercial use.</li>
              <li>You may share your storybook with family and friends but may not resell or commercially distribute the generated content.</li>
              <li>The OurFable brand, logo, and platform are our intellectual property.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">10. Acceptable Use</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 text-brand-ink-light text-sm leading-relaxed space-y-2">
              <li>Upload photos of people without their consent (or their guardian&apos;s consent for minors).</li>
              <li>Use the Service to generate harmful, abusive, or inappropriate content.</li>
              <li>Attempt to reverse-engineer, hack, or disrupt the Service.</li>
              <li>Use automated tools to access the Service without permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">11. Limitation of Liability</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed">
              OurFable.ai is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the specific product giving rise to the claim.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">12. Changes to Terms</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed">
              We reserve the right to modify these terms at any time. We will notify users of significant changes via email or prominent notice on our website. Continued use of the Service after changes constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-brand-ink mb-3">13. Contact</h2>
            <p className="text-brand-ink-light text-sm leading-relaxed">
              For questions about these terms, contact us at <a href="mailto:legal@ourfable.ai" className="text-brand-teal hover:underline">legal@ourfable.ai</a>.
            </p>
          </section>
        </div>
      </div>

      <footer className="border-t border-brand-border bg-white">
        <div className="max-w-5xl mx-auto px-4 py-8 text-center">
          <p className="text-brand-ink-muted text-sm font-body">
            &copy; 2026 OurFable.ai. All rights reserved.
          </p>
        </div>
      </footer>
    </main>
  );
}
